---
- name: Make sure ~/.ssh directory exists
  file:
    path: ~/.ssh
    state: directory
- name: Backup ssh config
  copy:
    src: ~/.ssh/config
    dest: "~/.ssh/config_{{ ansible_date_time.epoch}}"
  ignore_errors: true
  delegate_to: localhost
- name: generate host configuration
  template:
    src: "{{ item.template }}"
    dest: "{{ item.target }}"
    mode: 0644
  delegate_to: localhost
  loop:
    - { template: "templates/hosts.j2", target: "./hosts" }
    - { template: "templates/sshconfig.j2", target: "~/.ssh/config"}
- name: setting environment
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  loop:
    - "export LC_ALL=C.UTF-8"
    - "export LANG=C.UTF-8"